config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount LetterOpenerWeb::Engine => "letter_opener"
  end

  root 'auctions#index'

  get '/auth/github/callback', to: 'authentications#create'
  get '/logout', to: 'authentications#destroy'

  match 'auth/saml/callback', to: 'saml_authentications#create', via: [:get, :post]
  match 'auth/saml/logout', to: 'saml_authentications#destroy', via: [:get, :post, :delete]
  match 'auth/saml/setup', to: 'saml_authentications#setup', via: [:get, :post]

  get '/auctions/rules/sealed-bid', to: 'auctions#sealed_bid_auction_rules'
  get '/auctions/rules/reverse', to: 'auctions#reverse_auction_rules'
  get '/admin', to: 'admin/auctions/needs_attention#index'
  get '/admin/sign_in', to: 'admin/sign_ins#show'
  get '/sign_up', to: 'sign_ups#show'
  get '/sign_in', to: 'sign_ins#show'

  get '/api' => 'docs#index', as: 'api_doc'

  namespace :admin do
    resources :auction_reports, only: [:show]
    resources :auction_rejections, only: [:update]
    resources :auction_acceptances, only: [:update]
    resources :auction_mark_payments, only: [:update]
    resources :missed_deliveries, only: [:update]
    resources :user_reports, only: [:index]
    resources :proposals, only: [:create]
    resources :users, only: [:show, :edit, :update]

    namespace :auctions do
      get '/closed', to: 'closed#index'
      get '/needs_attention', to: 'needs_attention#index'
    end

    resources :auctions, except: [:index]

    scope '/people' do
      resources :admins, only: [:index]
      resources :vendors, only: [:index]
      resources :vendors, only: [:show] do
        resources :masquerades, only: [:new, :destroy]
      end
    end

    scope '/settings' do
      resources :customers, only: [:index, :new, :create, :edit, :update]
      resources :skills, only: [:index, :new, :create, :edit, :update]
    end
  end

  resources :auctions, only: [:index, :update]

  resources :auctions, only: [:show] do
    resources :bids, only: [:create]
    resources :receipts, only: [:new, :create]

    get 'receipt', to: 'receipts#show'
  end

  resources :users, only: [:update]
  get 'account/profile', to: 'users#edit', as: 'profile'
  get 'account/bids', to: 'bids#index', as: 'bids_placed'

  resources :insights, only: [:index]

  # Map current API requests to new controller for now
  namespace :api, defaults: { format: 'json' } do
    namespace :v0 do
      resources :auctions, only: [:index, :show] do
        resources :bids, only: [:create]
      end

      namespace :admin do
        resources :auctions, only: [:index, :show]
        resources :users, only: [:index]
      end

      get 'business_day', to: 'business_days#show'
    end
  end
end

app/views/admin/_auctions_subnav.html.erb
<h2>Auctions</h2>

<nav class="site-nav-secondary">
  <ul>
    <li><%= link_to t('links_and_buttons.auctions.needs_attention'),
      admin_auctions_needs_attention_path,
      class: view_model.needs_attention_auctions_nav_class %>
      <%= render partial: view_model.needs_attention_count_partial,
          locals: {count: view_model.needs_attention_auctions_count} %>
    </li>
    <li><%= link_to t('links_and_buttons.auctions.closed'),
      admin_auctions_closed_path,
      class: view_model.closed_auctions_nav_class %></li>
    <li class='new-button'>
      <%= link_to t('links_and_buttons.auctions.add'),
        new_admin_auction_path,
        class: 'settings-new usa-button usa-button-outline' %>
    </li>
  </ul>
</nav>

app/views/admin/_nav.html.erb
<aside class="usa-width-one-sixth">
  <ul class="usa-sidenav-list">
    <li><%= link_to 'Auctions',
      admin_path,
      class: view_model.auctions_nav_class %></li>
    <li><%= link_to 'Users',
      admin_users_path,
      class: view_model.users_nav_class %></li>
    <li><%= link_to 'Draft Auctions',
      admin_drafts_path,
      class: view_model.drafts_nav_class %></li>
    <li><%= link_to 'Action Items',
      admin_action_items_path,
      class: view_model.action_items_nav_class %></li>
    <li><%= link_to 'Create New Auction',
      new_admin_auction_path,
      class: view_model.new_auction_nav_class %></li>
  </ul>
</aside>

app/views/admin/_needs_attention_auction_count.html.erb
<span class="subnav-number-label"><%= count %></span>

app/views/admin/_people_subnav.html.erb
<h2>People</h2>

<nav class="site-nav-secondary">
<ul>
  <li><%= link_to 'Admins', admin_admins_path, class: view_model.admins_nav_class %></li>
  <li><%= link_to 'Vendors', admin_vendors_path, class: view_model.vendors_nav_class %></li>
  <%= render partial: view_model.csv_download_partial %>
</ul>
</nav>

app/views/admin/_settings_subnav.html.erb
<h2>Settings</h2>

<nav class="site-nav-secondary">
<ul>
  <li><%= link_to 'Customers', admin_customers_path, class: view_model.customers_nav_class %></li>
  <li><%= link_to 'Skills', admin_skills_path, class: view_model.skills_nav_class %></li>
  <li class='new-button'><%= render partial: view_model.new_button_partial %></li>
</ul>
</nav>